DROP TABLE IF EXISTS companies_raw;

CREATE TABLE companies_raw (
  "CompanyName" TEXT,
  "CompanyNumber" TEXT PRIMARY KEY,
  "RegAddress.CareOf" TEXT,
  "RegAddress.POBox" TEXT,
  "RegAddress.AddressLine1" TEXT,
  "RegAddress.AddressLine2" TEXT,
  "RegAddress.PostTown" TEXT,
  "RegAddress.County" TEXT,
  "RegAddress.Country" TEXT,
  "RegAddress.PostCode" TEXT,
  "CompanyCategory" TEXT,
  "CompanyStatus" TEXT,
  "CountryOfOrigin" TEXT,
  "DissolutionDate" TEXT,
  "IncorporationDate" TEXT,
  "Accounts.AccountRefDay" TEXT,
  "Accounts.AccountRefMonth" TEXT,
  "Accounts.NextDueDate" TEXT,
  "Accounts.LastMadeUpDate" TEXT,
  "Accounts.AccountCategory" TEXT,
  "Returns.NextDueDate" TEXT,
  "Returns.LastMadeUpDate" TEXT,
  "Mortgages.NumMortCharges" TEXT,
  "Mortgages.NumMortOutstanding" TEXT,
  "Mortgages.NumMortPartSatisfied" TEXT,
  "Mortgages.NumMortSatisfied" TEXT,
  "SICCode.SicText_1" TEXT,
  "SICCode.SicText_2" TEXT,
  "SICCode.SicText_3" TEXT,
  "SICCode.SicText_4" TEXT,
  "LimitedPartnerships.NumGenPartners" TEXT,
  "LimitedPartnerships.NumLimPartners" TEXT,
  "URI" TEXT,
  "PreviousName_1.CONDATE" TEXT,
  "PreviousName_1.CompanyName" TEXT,
  "PreviousName_2.CONDATE" TEXT,
  "PreviousName_2.CompanyName" TEXT,
  "PreviousName_3.CONDATE" TEXT,
  "PreviousName_3.CompanyName" TEXT,
  "PreviousName_4.CONDATE" TEXT,
  "PreviousName_4.CompanyName" TEXT,
  "PreviousName_5.CONDATE" TEXT,
  "PreviousName_5.CompanyName" TEXT,
  "PreviousName_6.CONDATE" TEXT,
  "PreviousName_6.CompanyName" TEXT,
  "PreviousName_7.CONDATE" TEXT,
  "PreviousName_7.CompanyName" TEXT,
  "PreviousName_8.CONDATE" TEXT,
  "PreviousName_8.CompanyName" TEXT,
  "PreviousName_9.CONDATE" TEXT,
  "PreviousName_9.CompanyName" TEXT,
  "PreviousName_10.CONDATE" TEXT,
  "PreviousName_10.CompanyName" TEXT,
  "ConfStmtNextDueDate" TEXT,
  "ConfStmtLastMadeUpDate" TEXT
);

